config/routes.rb
Chaptrak::Application.routes.draw do
  resources :locations
  resources :abouts, path: 'about'
  resources :chaprooms, path: 'chaproom'
  resources :reviews
  resources :chaps
  resources :dashboards, path: 'dashboard'
  resources :posts
  
  devise_for :users

  root to: "home#index"


end

app/models/comments.rb
class Comments < ActiveRecord::Base
  belongs_to :post
end

app/models/location.rb
class Location < ActiveRecord::Base
geocoded_by :address
after_validation :geocode, :if => :address_changed?
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :author
  validates_presence_of :body

  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

  def index

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardsController < ApplicationController

  def index

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]
  # GET /locations
  # GET /locations.json
  def index
    if params[:search].present?
      @locations = Location.near(params[:search], 50)
    else
      @locations = Location.all
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path, notice: 'Post saved!'
    else
      redirect_to posts_path, notice: 'Error: post not saved'
    end
  end

  protected
  def post_params
    params.require(:post).permit(:title, :author, :body, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/abouts/index.html.erb
<h1> <strong> CHAPTRAK: THE BEGINNING </strong> </h1>

<%= image_tag("Chaptrak13.jpg") %>
<%= image_tag("Chaptrak8.jpeg") %>

<h5>   It was a day like any other day. It was a frigid winter day in the exotic town of China(town) and Launch Academy was in full swing. Launchers were going about their normal routines....coding, sleeping, taking pictures of each other sleeping, and sleeping while dreaming about sleep. It was only after Dan's riveting afternoon lecture on Instance Methods that Greg arose from his post lunch slumber and noticed something odd. There was something on the floor underneath the whiteboard table (the very same one on which he had just attempted to draw an LOLcat!) "Hmmm," Greg thought to himself. "What in Sandi Metz's name could this possibly be?" As he reached down to pick up the strange object, he gasped in horror. "How could this be?!" Greg thought to himself (We have tried to recreate the look of disgust and outrage that Greg had initially experienced. However, even this photo culd not quite capture Greg's true feelings at the time). Alas, it was an unidentified tube of Chapstick. Not just any Chapstick. A Chapstick so nondescript, so utterly devoid of any information that the impossibility of linking it back to its owner was, indeed, quite horrifying.
</h5>

<p>


</p>




<h5>

   "What could possibly be done to remedy this situation?!" thought Greg. He racked his brain for any possible solution, but found none. Desperate, he turned to Lydia for advice. At first, Lydia was speechless. She couldn't imagine how the former Chapstick owner could possibly survive their days without the luxurious lip moisture that their abandoned Chapstick had previously provided them. Greg and Lydia took a moment of silence to mourn the poor, abandoned Chapstick and tried to go back to their normal Launch routines. However, that night Lydia went back to her Krash Pad and couldn't shake the fact that something had to be done. She talked to her friend Jake about the Chapstick catastrophe and he vowed to fix disastrous situations like these, once and for all. Jake thought for hours but no solution came to mind. Feeling defeated and exhausted, Jake went to bed. It was just past midnight when Jake sprung from his bed and shouted for joy. He had dreamt of an idea so exquisite, so mindblowingly revolutionary, that it must be immediately created and shared for the world to enjoy. His idea was simple. The results: life-changing. Not only could this Chapstick be returned back to its proper owner, but there was a way for millions of lost Chapsticks of to be returned to their owners! Thus, ChapTrak was born. The world was right once again.

   *Note: All true facts have been changed to protect the integrity of ChapTrak.

</h5>


<h1> THE CHAPTRAK TEAM </h1>
</p>

<%= image_tag("Chaptrak12.jpg") %>
<%= image_tag("Chaptrak9.jpg") %>
<%= image_tag("Chaptrak10.jpg") %>
<%= image_tag("Chaptrak14.JPG") %>

<h1> </h1>
<br>

app/views/dashboard/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Welcome to Chaptrak!</title>
  </head>



</html>

app/views/home/index.html.erb
<head>
  <title>Geolocation</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
</head>
  <body>
    <%= image_tag("chaptrak_img.jpg") %>
  </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta name="google-site-verification" content="93dIUokTQmvpbTzuSVxnq1wWWriIJyk2EcitzKPwa6w" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Chaptrak</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  </head>
    <title><%= content_for?(:title) ? yield(:title) : "Chaptrak" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
    <body>

      <div class="row">
        <nav class="top-bar" data-topbar>
          <ul class="title-area">
            <li class="name">
              <h1><a href="/">CHAPTRAK</a></h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
          </ul>
          <section class="top-bar-section">
            <ul class="right">
              <% if user_signed_in? %>
                <li><%= "Signed in as #{current_user.email}" %></li>
                <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li><%= link_to 'Sign In', new_user_session_path %></li>
                <li><%= link_to 'Sign Up', new_user_registration_path %></li>
              <% end %>
            </ul>
            <ul class="left">
              <li class="has-dropdown">
                <a href="/locations">LOCATIONS</a>
                <ul class="dropdown">
                  <li><a href="/locations/new">New Location</a></li>
                </ul>
              </li>
            </ul>
            <ul class="left">
              <li class="has-dropdown">
                <a href="/posts">POSTS</a>
                <ul class="dropdown">
                  <li><a href="/posts/new">NEW POSTS</a></li>
                </ul>
              </li>
            </ul>
            <ul class="left">
              <li class="">
                <a href="/about">ABOUT</a>
              </li>
            </ul>
          </section>
        </nav>

        <%= yield %>

      </div>
    </body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<br>
<br>
<h4><strong>SEARCH</strong></h4>
<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Nearby Locations", :name => nil %>
  </p>
<% end %>
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

<h3>Nearby locations</h3>
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>
<p>
<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Destroy', @location, :confirm => "Are you sure?", :method => :delete %> |
<%= link_to 'Back', locations_path %>
</p>

app/views/posts/index.html.erb
<h1> All Posts </h1>
<%@posts.each do |post|%>
<%= link_to post.title, "/posts/#{post.id}" %> <br />
<% end %>
<p></p>
<p></p>
<p></p>
<%=link_to 'Make a New Post!', new_post_path%>

app/views/posts/new.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title%>
  <%= f.hidden_field :author, value: current_user.id, readonly: true%>
  <%= f.input :body%>

  <%= f.button :submit, class: 'button' %>

<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1><%=@post.title%></h1>

<p><%=@post.body%></p>

<p><%=link_to 'All Posts', posts_path%></p>